# .travis.yml

language: c

sudo: true

addons:
  apt:
    packages:
      - libpam-dev

script:
  - ./configure --prefix=/usr --with-openssl --with-pam_mods_dir=/lib/security --with-pam=/usr
  - make
