language: c
sudo: true

addons:
  apt:
    packages:
      - clang
      # these packages are needed for urllib3[secure] for SNI support
      # (they may not be installed on all Travis build nodes)
      - build-essential
      - python-dev
      - libffi-dev
      - libssl-dev

compiler:
  - clang
  - gcc
  - scan-build
  - debian

script: ./.travis.sh
